#!/usr/bin/env bash
# Installs ingnx and configures it

apt-get update

apt-get install -y nginx

echo "Hello World!" | tee /var/www/html/index.html

cat <<EOF | tee /etc/nginx/sites-available/default
server {
    listen 80;
    server_name _;

    location / {
             root /var/www/html;
             index index.html;
    }
}
EOF

sudo service nginx restart
