#!/usr/bin/env bash
# Configures Nginx for redirection with a 301 Moved Permanently using sed

apt-get update

apt-get install -y nginx

echo "Hello Kelvino!" | tee /var/www/html/index.html

cat <<EOF | tee /etc/nginx/sites-available/default
server {
    listen 80;
    server_name _;

    root /etc/nginx/html;
    index index.html;

    location /redirect_me {
      return 301 http://kelvino.com;
    }
}
EOF

sudo service nginx restart
