#!/usr/bin/env bash
# Configures Nginx for redirection with a 301 Moved Permanently using sed
# Create a simple HTML file for redirection
echo "<html><head><meta http-equiv=\"refresh\" content=\"0;url=https://www.youtube.com/watch?v=QH2-TGUlwu4\"></head></html>" | tee /var/www/html/redirect_me.html

# Configure Nginx for redirection with a 301 Moved Permanently using sed
nginx_config="/etc/nginx/sites-available/default"

# Use sed to modify the Nginx configuration
sed -i '/location \/ {/a \\n    location \/redirect_me {\n        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n    }' "$nginx_config"

# Restart Nginx to apply the changes
service nginx restart

