#!/usr/bin/env bash
# Configures Nginx for redirection with a 301 Moved Permanently using sed

cat <<EOF | tee /etc/nginx/sites-available/default
server {
    listen 80;
    listen [::]:80;

    root /etc/nginx/html;
    index index.html index.htm;

    location /redirect_me {
      return 301 http://kelvino.com;
    }
}
EOF

sudo service nginx restart
