#!/usr/bin/env bash
# Configures web-02 to be identical to web-01 server

sudo apt-get upgrade

sudo apt-get install -y nginx

HOSTNAME=$(hostname)

cat <<EOF | sudo tee /etc/nginx/sites-available/default
server {
     listen 80;
     server_name _;

     root /var/www/html;
     index index.html;

     location /redirect_me {
       return 301 http://kelvino.com;
     }

     error_page 404 /404.html;
     location = /404.html {
        root /var/www/html;
     }

     add_header X-Served-By $HOSTNAME;
}
EOF

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo service nginx restart
