#!/usr/bin/env bash
# Configures web-02 to be identical to web-01 server

sudo apt-get -y upgrade

sudo apt-get -y install nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html

echo "Hello World!" | sudo tee /etc/nginx/html/index.html

cat <<EOF | sudo tee /etc/nginx/sites-available/default
server {
     listen 80;
     listen [::]:80;
     server_name _;
     add_header X-Served-By "$HOSTNAME";
     root /etc/nginx/html;
     index index.html index.htm;

     location /redirect_me {
       return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
     }

     error_page 404 /404.html;
     location /404 {
        root /etc/nginx/html;
        internal;
     }
}
EOF

echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

sudo service nginx restart
