#!/usr/bin/env bash
# Install and configure HAProxy version 2.6-stable(LTS)
# with the following settings:

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get update
sudo apt-get install -y haproxy=2.6\*

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

echo "frontend web
         bind *:80
         mode http
         default_backend web_backend
backend web_backend
    mode http
    balance roundrobin
    server 331584-web-01 54.157.190.140:80 check
    server 331584-web-02 52.23.179.51:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy restart
