#!/usr/bin/env bash
# Install and configure HAProxy version 2.6-stable(LTS)
# with the following settings:

sudo apt-get update

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get -y install haproxy=2.6\*

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend web
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server 331584-web-01 54.157.190.140:80 check
    server 331584-web-02 52.23.179.51:80 check
EOF

sudo systemctl restart haproxy
sudo systemctl enable haproxy
