#!/usr/bin/env bash
#Displays the content of the file /etc/passwd
if [ ! -f "/etc/passwd" ]; then
	echo "File does not exist"
else
	while IFS= read -r line
	do
		echo "$line" | cut -d ":" -f1,4,6
	done < "/etc/passwd"
fi
